Fix for 'history package-list'
rpm-software-management/yum pull request #32
Opened 2017-01-04 09:11 UTC by upadhyeammit

The 'yum history package-list package-name' fails to work when transactions for that package are greater than 128(PATTERNS_INDEXED_MAX). This fixes the SQL query.

2017-01-04 17:02 UTC, dmnks approved these changes
Looks good to me, thanks!

2017-01-04 17:07 UTC, dmnks commented
Just a quick reproducer:

1. change yum.constants.PATTERNS_INDEXED_MAX to 1
2. update a package via "yum update foo"
3. run "yum history packages-list foo"

This would return an empty table before the patch.

2017-01-04 17:21 UTC, dmnks requested changes
Actually, I just spotted small a issue with your commit: You didn't set user.name and user.email in your git config correctly. Could you please follow https://help.github.com/articles/set-up-git/ and repush a new commit?

Thanks!

2017-01-05 05:53 UTC, upadhyeammit commented
Hello Michal, 

Added details as you mentioned and merged it. Request to review.

Thank You!

2017-01-05 10:00 UTC, dmnks approved these changes
LGTM!

2017-01-05 14:43 UTC, james-antill commented
It's very likely that this bug is identical in dnf, so someone might want to ping them :)

2017-01-05 15:10 UTC, upadhyeammit commented
Hello James,

Sent PR for dnf too: https://github.com/rpm-software-management/dnf/pull/698

2017-02-02 14:58 UTC, merged